apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: 'http://10.42.0.16/root/test.git'
  username: root
  password: new_password