apiVersion: v1
kind: Service
metadata:
  name: gitlab-server
  namespace: gitlab
spec:
  selector:
    app: gitlab-ce
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
  type: LoadBalancer
