## VARIABLES
CONTROLLER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

CONTROLLER_NAME = "bapasquiS"
WORKER_NAME = "bapasquiSW"

MEM = 1024
CORE = 1

## VAGRANT CONFIG
Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  
  config.vm.define CONTROLLER_NAME do |controller|
    controller.vm.hostname = CONTROLLER_NAME
    controller.vm.provider "virtualbox" do |v|
      v.memory = MEM
      v.cpus = CORE
      v.name = CONTROLLER_NAME
    end
    controller.vm.network "private_network", type: "static", ip: CONTROLLER_IP
    controller.vm.provision "shell", path: "scripts/controller.sh", args: [CONTROLLER_IP]
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.provider "virtualbox" do |v|
      v.memory = MEM 
      v.cpus = CORE
      v.name = WORKER_NAME
    end
    worker.vm.network "private_network", type: "static", ip: WORKER_IP
    worker.vm.provision "shell", path: "scripts/worker.sh", args: [CONTROLLER_IP, WORKER_IP]
  end
end
