Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
  
  config.vm.define "dboire" do |dboire|
    dboire.vm.hostname = "server1S"
    config.vm.network "private_network", ip: "192.168.56.110"
    dboire.vm.provision "shell", inline: <<-SHELL
    #curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -
    SHELL
  end

  config.vm.define "hbelle" do |hbelle|
    hbelle.vm.hostname = "server2SW"
    config.vm.network "private_network", ip: "192.168.56.111"
    hbelle.vm.provision "shell", inline: <<-SHELL
    #curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" sh -
    SHELL
  end

end
